audit_header: false
title: Scottsdale Real Estate Video Blog with Mark Deacon
description: Our mission at Remax Fine Properties is to be your best resource for Scottsdale real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Remax Fine Properties, your professional Scottsdale Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Mark Deacon
  title:
  license_number:
  about_markdown: |
    Experienced Business Owner and Royal Canadian Air force Veteran with a demonstrated history of working in the real estate industry. Skilled in Operations Management, Sales, Team Building, Public Speaking, and Real Estate Transactions. Strong entrepreneurship professional graduated from American Military University.
  brand: Remax Fine Properties
  brokerage:
  market: Scottsdale
  address: 18281 North Pima Road
  phone: 623-335-0485
  phone_type:
  phone2:
  phone2_type:
  email: Mark@MarkDeaconTeam.com
  url: http://www.ViewAllPhoenixAreaHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.viewallphoenixareahomes.com/homevalue/searchandmatch
  second_CTA_text: Home Search
  second_CTA_URL: https://www.viewallphoenixareahomes.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Scottsdale Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.viewallphoenixareahomes.com/homevalue/searchandmatch

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Scottsdale Home?"
    CTA_text2: "Search the entire MLS for your Scottsdale home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.viewallphoenixareahomes.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/deacongroup/
  linkedin_url: https://www.linkedin.com/in/mark-deacon-734b6019/
  youtube_url: https://www.youtube.com/channel/UCAYrOI6hmefYG0Wl0A5Arkg
  twitter_url: https://twitter.com/TheDeaconGroup
  instagram_url: https://www.instagram.com/thedeacongroup1/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Scottsdale Real Estate Podcast with Mark Deacon'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Scottsdale Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Remax Fine Properties - your professional Scottsdale Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Scottsdale, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Mark Deacon'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Scottsdale Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#0066b2'
  theme_color: '#7a7c7e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
